## THIS FILE HOLDS ALL MODELS_ML_FINAL HYPERPARAMETERS

# LightGBM: static parameters
lgbm_static_params:
    boosting_type: 'dart'
    extra_trees: True
    n_jobs: 23
    n_iter: 500
    # random_state=377507,  # lowest std random_state from testing
    # bagging_freq=10 for future


## LIGHTGBM COARSE TUNING
# LightGBM: coarse tuning parameters (not used in kedro pipeline)
lgbm_coarse_tune_params:
    lgbm_model__n_estimators: np.linspace(50, 1750, 25, dtype=int)  # alias: num_iterations
    lgbm_model__learning_rate: np.round(np.linspace(0.01, 0.05, 25), 3)
    lgbm_model__max_depth: np.linspace(200, 750, 25, dtype=int)
    lgbm_model__reg_lambda: np.round(np.linspace(5, 20, 25), 3)  # alias: lambda_l2
    lgbm_model__num_leaves: np.linspace(2, 200, 25, dtype=int)
    lgbm_model__max_bin: np.linspace(30, 350, 25, dtype=int)
#  bagging_fraction: np.linspace(0.5, 1, 26)
#  min_data_in_leaf: np.linspace(2, 100, 50, dtype=int)
#  path_smooth: np.linspace(0, 10, 21)

# LightGBM best coarse tuning parameters
lgbm_coarse_best_params:
    n_estimators: 262
    learning_rate: 0.012
    max_depth: 222
    reg_lambda: 6.25
    num_leaves: 2
    max_bin: 296



## LIGHTGBM FINE-TUNING
# LightGBM: fine-tuning parameters
lgbm_fine_tune_params:
    lgbm_model__n_estimators: [50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
                               180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
                               310, 320, 330, 340, 350]
    lgbm_model__learning_rate: [0.01, 0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018, 0.019, 0.02]
    lgbm_model__max_depth: [100, 110, 120, 130, 140, 150, 160, 170,
                            180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
                            310, 320, 330, 340, 350]
    lgbm_model__reg_lambda: [5.0, 5.625, 6.25, 6.875, 7.5, 8.125, 8.75, 9.375,
                             10.0, 10.625, 11.25, 11.875, 12.5, 13.125, 13.75, 14.375,
                             15.0, 15.625, 16.25, 16.875, 17.5, 18.125, 18.75 , 19.375, 20.0]
    lgbm_model__num_leaves: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
                             36, 38, 40, 42, 44, 46, 48, 50]
    lgbm_model__max_bin: [30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150,
                          160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280,
                          290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
                          420, 430, 440, 450, 460, 470, 480, 490, 500]
